# -*- mode: ruby -*-
# vi: set ft=ruby :
# Every Vagrant development environment requires a box. You can search for
# boxes at https://atlas.hashicorp.com/search.

ENV["LC_ALL"] = "en_US.UTF-8"

BOX_IMAGE = "debian/contrib-jessie64"
NODE_COUNT = 2
MEMORY = 1024

Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = MEMORY
        v.cpus = 1
    end
    config.vm.define "master" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "puppet.puppet.vm"
        subconfig.vm.network "public_network"
        subconfig.vm.network :private_network, ip: "10.12.0.10"
    end
    (1..NODE_COUNT).each do |i|
        config.vm.define "node#{i}" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "node#{i}.puppet.vm"
        subconfig.vm.network "public_network"
        subconfig.vm.network :private_network, ip: "10.12.0.#{i + 10}"
        end
    end

# Provisioning
    config.vm.provision "default", type: "shell", inline: <<-SHELL
      echo "-=PROVISION DEFAULT STAGE=-"
      #if [ ! -d "/home/vagrant/map" ]; then ln -s /vagrant/exchange /home/vagrant/map; fi
      sudo echo 'Acquire::http::Proxy "http://proxy.example.com:8080";' >> /etc/apt/apt.conf
      sudo echo 'Acquire::::Proxy "true";' >> /etc/apt/apt.conf
      sudo echo '10.12.0.10       puppet' >> /etc/hosts
      sudo echo '10.12.0.10       puppet.puppet.vm' >> /etc/hosts
      sudo echo '10.12.0.11       node1.puppet.vm' >> /etc/hosts
      sudo echo '10.12.0.11       node2.puppet.vm' >> /etc/hosts
      sudo echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
      sudo apt-get update
      sudo apt-get upgrade -qq
      sudo apt-get install mc -qq
      sudo apt-get install vim -qq
      sudo apt-get install python3 -qq
      sudo apt-get install python-pip -qq
      sudo apt-get install git -qq
    SHELL

    config.vm.provision "master", type: "shell", inline: <<-SHELL
      echo "-=PROVISION MASTER STAGE=-"
      sudo rm /etc/apt/sources.list.d/*
      sudo echo 'deb http://ftp.debian.org/debian jessie-backports main' >> /etc/apt/sources.list.d/backports.list
      sudo apt-get update
      sudo apt-get -t jessie-backports install puppet-master -qq
      sudo echo '[main]' > /etc/puppet/puppet.conf
      sudo echo 'ssldir = /var/lib/puppet/ssl' >> /etc/puppet/puppet.conf
      sudo echo '[master]' >> /etc/puppet/puppet.conf
      sudo echo 'vardir = /var/lib/puppet' >> /etc/puppet/puppet.conf
      sudo echo 'cadir  = /var/lib/puppet/ssl/ca' >> /etc/puppet/puppet.conf
      sudo echo 'dns_alt_names = puppet.puppet.vm' >> /etc/puppet/puppet.conf
      sudo echo '*.vm' >> /etc/puppet/autosign.conf
      sudo echo 'JAVA_ARGS="-Xms512m -Xmx512m-XX:MaxPermSize=256m"' >> /etc/default/puppet-master
      sudo gem install r10k
      echo "Puppet Master-Server configure - completed"
    SHELL

    config.vm.provision "node", type: "shell", inline: <<-SHELL
      echo "-=PROVISION NODES STAGE=-"
      sudo rm /etc/apt/sources.list.d/*
      sudo echo 'deb http://ftp.debian.org/debian jessie-backports main' >> /etc/apt/sources.list.d/backports.list
      sudo apt-get update
      sudo apt-get -t jessie-backports install puppet -qq
      sudo apt-get install -t jessie-backports openjdk-8-jdk -qq
      sudo echo 'START=yes' > /etc/default/puppet
      sudo echo '[main]' > /etc/puppet/puppet.conf
      sudo echo 'ssldir = /var/lib/puppet/ssl' >> /etc/puppet/puppet.conf
      sudo echo '[agent]' >> /etc/puppet/puppet.conf
      sudo echo 'vardir = /var/lib/puppet' >> /etc/puppet/puppet.conf
      sudo echo 'cadir  = /var/lib/puppet/ssl/ca' >> /etc/puppet/puppet.conf
      sudo echo 'server = puppet.puppet.vm' >> /etc/puppet/puppet.conf
      sudo echo 'runinterval = 1m ' >> /etc/puppet/puppet.conf
      echo "Puppet Agent configure - completed"
    SHELL
end
